config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#accueil'

  get '/team', to: 'pages#team', as: 'team' 

  get '/contact', to: 'pages#contact', as: 'contact' 

  get 'welcome(/:first_name)', to: 'pages#welcome', as: 'welcome' 

  get 'potin/:id', to:'pages#potin', as: 'potin'

  get 'potin/auteur/:title', to:'pages#auteur', as: 'auteur'

  resources :gossips #, only [:new, :create]

  root to: 'utilisateurs#new'

  #get '/profil', to: 'utilisateurs#edit', as: :profil
  #patch '/profil' to: 'utilisateurs#update'

  resources :sessions, only: [:new, :create, :destroy]

  resources :utilisateurs, only: [:new, :create] do 
    member do 
      get 'confirm'
    end
  end

end

app/models/affiliation.rb
#La table de jointure appartient à Gossip et Tag

class Affiliation < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
#Une ville a plusieurs users

class City < ApplicationRecord
  has_many :users

  validates :name, 
    presence: true
  #validates :zip_code,
   # presence : true
end

app/models/gossip.rb
#Gossip appartient à un User et a plusieurs tags

class Gossip < ApplicationRecord
  belongs_to :user
  has_many :affiliations
  has_many :tags, through: :affiliations

  validates :title, 
    length: { minimum: 3, maximum: 14 }
  validates :content, 
    presence: true
end

app/models/tag.rb
#Un tag peut avoir plusieurs gossips

class Tag < ApplicationRecord
  has_many :affiliations
  has_many :gossips, through: :affiliations

  validates :title, 
    presence: true
end

app/models/user.rb
#Un User appartient à une ville et peut avoir plusieurs gossips

class User < ApplicationRecord
  belongs_to :city
  has_many :gossips

  validates :first_name, 
    presence: true
  validates :last_name, 
    presence: true
  validates :description, 
    length: { minimum: 5 }, 
    length: { maximum: 50 }
  validates :email, 
    #presence: true
    uniqueness: true
  #validates :age, 
    #numericality : true
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord

  has_secure_password
  has_secure_token :confirmation_token

  validates :username, 
    format: {with: /\A[a-zA-Z0-9_]{2,20}\z/, message:"ne doit contenir que des caractères alphanumériques ou des _"},
    uniqueness: {case_sensitive: false}

  validates :email, 
    format: {with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/},
    uniqueness: {case_sensitive: false}

  def to_session
    {id: id}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :only_signed_in
  add_flash_types :success, :danger

  private 

  def only_signed_in
    if !session[:auth] || !session[:auth]['id']
      redirect_to new_utilisateur_path, danger: "Vous n'avez pas le droit d'accèder à cette page"
    end
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  def index 
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    @gossip = Gossip.new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create 
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    @gossip = Gossip.new(
      'title' => params[:title],
      'content' => params[:content],
      'user_id' => User.all.sample.id
    )
      if @gossip.save
        puts "c'est sauvegardé"
        redirect_to root_path
      else 
        puts "echec"
        render 'new'
      end
  end

  def edit 
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(tes_params)
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy 
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

end  

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  #Définition de la page d'accueil
  def accueil
    puts params.inspect
    @gossips = Gossip.all
    @users = User.all
  end

  #Définition de la page Team
  def team
  end

  #Définition de la page Contact
  def contact
  end

  #Définition de la page Welcome
  def welcome
    @first_name = params[:first_name]
    puts params[:first_name].inspect
  end

  #définition de la page potin 
  def potin
    @gossips = Gossip.all
    @id = params[:id]
  end

  #définition de la page auteur 
  def auteur
  @gossips = Gossip.all
  @title = params[:title]
  end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_action :only_signed_in, only: [:new, :create]
  
  def new

  end

  def create
    utilisateur_params = params.require(:utilisateur)
    @utilisateur = Utilisateur.where(username: utilisateur_params[:username]).or(Utilisateur.where(email: utilisateur_params[:username])).first
    if @utilisateur and @utilisateur.authenticate(utilisateur_params[:password])
      session[:auth] = @utilisateur.to_session
      redirect_to profil_path, success: 'Connexion réussie'
    else 
      redirect_to new_session_path, danger: 'Identifiants incorrects'
    end
  end

  def destroy
  end

end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create, :confirm]

  def new 
    @utilisateur = Utilisateur.new
  end 

  def create 
    utilisateur_params = params.require(:utilisateur).permit(:username, :email, :password, :password_confirmation)
    @utilisateur = Utilisateur.new(utilisateur_params)
    if @utilisateur.valid?
      @utilisateur.save
      UtilisateurMailer.confirm(@utilisateur).deliver_now
      redirect_to new_utilisateur_path, success: 'Votre compte a bien été créé, vous devriez recevoir un email pour confirmer votre compte'
      #render 'new'
    else 
      render 'new'
    end
  end 

  def confirm 
    @utilisateur = Utilisateur.find(params[:id])
    if @utilisateur.confirmation_token == params[:token]
      @utilisateur.update_attributes(confirmed: true, confirmation_token: nil)
      @utilisateur.save(validate: false)
      session[:auth] = @utilisateur.to_session
      redirect_to profil_path, success: 'Votre compte a bien été confirmé'
    else 
      redirect_to new_utilisateur_path, danger: 'Ce token ne semble pas valide'
    end 
  end

  def edit 
    @utilisateur = Utilisateur.find(session[:auth]['id'])
  end

  def update 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/gossip/edit.html.erb
<h1>Modif formulaire</h1>

<%= form_tag url_for(action: 'edit'), method: "get" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

<% end %>

app/views/gossip/new.html.erb
<h1>View formulaire</h1>

<%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

<% if @gossip.errors.any? %>
              <%@gossip.errors.full_messages.each do |message| %>
                <%if message == "Title can't be blank" %>
                  <div class="container alert alert-danger d-flex align-items-center p-1 mt-1" roler="alert"><%= message %></div>
                <% end %>
              <% end %>
            <% end %>

            <% if @gossip.errors.any? %>
              <%@gossip.errors.full_messages.each do |message| %>
                <%if message == "Title is too short (minimum is 3 characters)" %>
                  <div class="container alert alert-danger d-flex align-items-center p-1 mt-1" roler="alert"><%= message %></div>
                <% end %>
              <% end %>
            <% end %>

            <% if @gossip.errors.any? %>
              <%@gossip.errors.full_messages.each do |message| %>
                <%if message == "Title is too long (maximum is 14 characters)" %>
                  <div class="container alert alert-danger d-flex align-items-center p-1 mt-1" roler="alert"><%= message %></div>
                <% end %>
              <% end %>
            <% end %>

            

    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">The Gossip Bad Bitch Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample02">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Accueil</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/team">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/welcome">Welcome</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_utilisateur_path %>">S'inscrire</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_session_path %>">Se connecter</a>
            </li>
          </ul>
          <!--<form>
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form> -->
        </div>
      </div>
    </nav>

    <div class="container" style="padding-top: 5rem;">
      <% if flash[:success] %>
        <div class="alert alert-success">
          <%= flash[:success] %>
        </div>
      <%end%>

      <% if flash[:danger] %>
        <div class="alert alert-danger">
          <%= flash[:danger] %>
        </div>
      <%end%>


      <%= yield %>

      <%= debug session[:auth] %>
    </div>
    <!-- Script Javascript Bootstrap en bas de page pour éviter de bloquer le chargement de la page -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/accueil.html.erb
<h1 class="row justify-content-center mb-5"> Bienvenue sur The Gossip Project</h1>
<p class="row justify-content-center mb-5" style="color:#C7C7F1"> Parcours le mur des gossips pour voir les dernières nouveautés</p>

 <a href="<%= new_gossip_path %>" class="btn btn-primary center">Créer un nouveau potin</a>
 </ br>  </ br>

 
<div class="container row justify-content-center">
<% @gossips.each do |gossip| %>


<div class="card mb-3 mx-4 card-home" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= gossip.title %></h5>
    <p class="card-text"><em><%= gossip.content%></em></p>
    <a href="potin/<%=gossip.id%>" class="btn btn-primary">Voir le potin</a>
  </div>
</div>
  <% end %> 
</div>

app/views/pages/auteur.html.erb
<div class="container" style="height:80vh">
  <h1>Voici la page de l'auteur : <span style="color:#8064A2"><%= @title%></span> </h1>
  <h3 class="mb-5">Ses articles :</h3>

  <div class="container row justify-content-center">
    <% @gossips.each do |gossip| %>
      <% if gossip.title == @title%>
        <div class="card mb-3 mx-4 card-home" style="width: 18rem;">
          <div class="card-body">
            <p class="card-text"><em><%= gossip.content %></em></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <a href="<%= root_path %>" class="btn btn-primary mt-3 rounded-pill">👈 Revenir au menu</a>
</div> 

app/views/pages/contact.html.erb
<!-- View HTML de notre page Contact-->
<div class="container contact " style="height:80vh">
	<div class="row">
		<div class="col-md-3">
			<div class="contact-info">
				<img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image"/>
				<h2>Vous pouvez nous contacter ici :</h2>
				<h4>Mais faites le uniquement si c'est important car ça ne fonctionne pas !</h4>
        <br/> <br/> 
			</div>
		</div>
		<div class="col-md-9">
			<div class="contact-form">
				<div class="form-group">
				  <label class="control-label col-sm-2" for="fname">Prénom :</label>
				  <div class="col-sm-10">          
					<input type="text" class="form-control" id="fname" placeholder="Ton petit prénom" name="fname">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="lname">Nom:</label>
				  <div class="col-sm-10">          
					<input type="text" class="form-control" id="lname" placeholder="Ton petit nom" name="lname">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="email">Email:</label>
				  <div class="col-sm-10">
					<input type="email" class="form-control" id="email" placeholder="Ton adresse mail de bg" name="email">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="comment">Commentaire:</label>
				  <div class="col-sm-10">
					<textarea class="form-control" rows="5" id="comment" placeholder="Une remarque ? Un petit conseil ?"></textarea>
				  </div>
				</div>
				<div class="form-group">        
				  <div class="col-sm-offset-2 col-sm-10">
					<button type="soumettre" class="btn btn-default">Envoyer</button>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/potin.html.erb
<div class="container" style="height:80vh">
    <% @gossips.all.each do |gossip| %>
      <% if gossip.id == @id.to_i%>
        <h3> Titre : <br><%= gossip.title %></h3>
        <p> Contenu :  <br><em><%= gossip.content %></em> </p>
        <p> Prénom de l'auteur :  <br><em><%= gossip.user.first_name %></em></p>
        <p> Ville de l'auteur :  <br><em><%= gossip.user.city.name %></em></p>



        <a href="<%= root_path %>" class="btn btn-primary m-3 rounded-pill">👈 Revenir au menu</a>
        <a href="/potin/auteur/:id" class=" btn-auteur btn btn-primary m-3 rounded-pill">Profil de l'auteur</a>
        <hr>
      <% end %>
    <% end %>
</div>

app/views/pages/team.html.erb
<!-- View HTML de notre page Team-->

<div class="py-5 team4">
  <div class="container">
    <div class="row justify-content-center mb-4">
      <div class="col-md-7 text-center">
        <h1 class="mb-3">Une sacrée équipe</h1>
        <h6 class="subtitle">Passionnés de potins depuis leur enfance, cette équipe de choc travaillent dans l'ombre pour votre plus grand plaisir...</h6>
        <h6 class="subtitle">Les mystérieux Loïc & Alex !</h6>

      </div>
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<h1>Bienvenue <span style="color: black"><%= @first_name %></span>
  <% if @first_name != nil%>
    ! </br></br><h3>T'as fais THP toi aussi ?! 🤣</h3>
  <%end%></h1>

</br>
<h3>⚠️ Dans l'URL rajoute à la fin "/ton_prénom" une fonction secrète t'attend...</h3>
</div>

app/views/utilisateurs/edit.html.erb
<% if @utilisateur.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @utilisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">S'inscrire</div> <br> <br>
  <div class="panel-body">
    <%= form_for @utilisateur, url: profil_path, html: {class: 'form-horizontal'} do |f| %>
      <div class="form-group">
        <%= f.label :username, "Nom d'utilisateur", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :email, "Email", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :password, "Mot de passe", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.password_field :password, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confimer le mot de passe", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
          <div class="col-md-offset-4 col-md-6">
            <button type="submit" class="btn btn-primary">
              S'inscrire
            </button>
          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/utilisateurs/new.html.erb
<% if @utilisateur.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @utilisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading"><H1>S'inscrire</H1></div> <br> <br>
  <div class="panel-body">
    <%= form_for @utilisateur, html: {class: 'form-horizontal'} do |f| %>
      <div class="form-group">
        <%= f.label :username, "Nom d'utilisateur", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :email, "Email", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :password, "Mot de passe", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.password_field :password, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confimer le mot de passe", class: 'col-md-4 control label' %>
          <div class="col-md-6">
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group">
          <div class="col-md-offset-4 col-md-6">
            <button type="submit" class="btn btn-primary">
              S'inscrire
            </button>
          </div>
        </div>

    <% end %>
  </div>
</div>